name: Build Works

on: push

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v3

      - name: <Add> Node/NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
          cache: npm

      - name: <Install> NPM
        run: npm install

      - name: <Build> Web-Extensions
        run: npm run build

      - name: <Artifact> Web-Extensions
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist



